//------------------------------------------------------------------------------
//
//    Terrain resource type
//
//    (C) 2026 Individual contributors, see AUTHORS file
//------------------------------------------------------------------------------
include "foundation/math.fbs";

namespace Render;

table TerrainResource
{
	min_height : float = 0.0;
	max_height : float = 128.0;
	world_size_x : float = 1024.0;
	world_size_z : float = 1024.0;
	tile_width : float = 64.0;
	tile_height : float = 64.0;
	quads_per_tile_x : float = 16.0;
	quads_per_tile_z : float = 16.0;
	height_map : string = "system:white:tex";
	decision_map : string = "system:white:tex";
	enable_ray_tracing : bool = false;
	biomes : [Biome];
}

table Biome
{
	mask : string = "system:white:tex";
	slope_threshold : float = 0.5;
	height_threshold : float = 0.5;
	uv_scale_factor : float = 1.0;
	materials: [BiomeMaterial];
}

table BiomeMaterial
{
	albedo : string = "system:white:tex";
	normals : string = "system:nobump:tex";
	material : string = "system:default_material:tex";
}

root_type TerrainResource;
file_identifier "TERE";
file_extension "nater";