//Header Generated with https://github.com/aiekick/ImGuiFontStudio
//Based on https://github.com/juliettef/IconFontCppHeaders

#pragma once

#define FONT_ICON_FILE_NAME_ttf "fontawesome-webfont.ttf"

#define ICON_MIN_ttf 0xf00c
#define ICON_MAX_ttf 0xf13e

#define ICON_ttf_ANGLE_DOWN u8"\uf107"
#define ICON_ttf_ANGLE_LEFT u8"\uf104"
#define ICON_ttf_ANGLE_RIGHT u8"\uf105"
#define ICON_ttf_ANGLE_UP u8"\uf106"
#define ICON_ttf_BAN_CIRCLE u8"\uf05e"
#define ICON_ttf_BOOK u8"\uf02d"
#define ICON_ttf_CHEVRON_LEFT u8"\uf053"
#define ICON_ttf_CHEVRON_RIGHT u8"\uf054"
#define ICON_ttf_CLOUD_DOWNLOAD u8"\uf0ed"
#define ICON_ttf_CLOUD_UPLOAD u8"\uf0ee"
#define ICON_ttf_COG u8"\uf013"
#define ICON_ttf_CROP u8"\uf125"
#define ICON_ttf_DESKTOP u8"\uf108"
#define ICON_ttf_EDIT u8"\uf044"
#define ICON_ttf_EXCLAMATION_SIGN u8"\uf06a"
#define ICON_ttf_FACETIME_VIDEO u8"\uf03d"
#define ICON_ttf_FOLDER_CLOSE u8"\uf07b"
#define ICON_ttf_FOLDER_CLOSE_ALT u8"\uf114"
#define ICON_ttf_FOLDER_OPEN u8"\uf07c"
#define ICON_ttf_FOLDER_OPEN_ALT u8"\uf115"
#define ICON_ttf_GITHUB_ALT u8"\uf113"
#define ICON_ttf_HOME u8"\uf015"
#define ICON_ttf_INFO_SIGN u8"\uf05a"
#define ICON_ttf_LAPTOP u8"\uf109"
#define ICON_ttf_LOCATION_ARROW u8"\uf124"
#define ICON_ttf_MICROPHONE u8"\uf130"
#define ICON_ttf_MICROPHONE_OFF u8"\uf131"
#define ICON_ttf_MINUS u8"\uf068"
#define ICON_ttf_MINUS_SIGN u8"\uf056"
#define ICON_ttf_MOBILE_PHONE u8"\uf10b"
#define ICON_ttf_OK u8"\uf00c"
#define ICON_ttf_OK_SIGN u8"\uf058"
#define ICON_ttf_PAUSE u8"\uf04c"
#define ICON_ttf_PICTURE u8"\uf03e"
#define ICON_ttf_PLAY u8"\uf04b"
#define ICON_ttf_PLUS u8"\uf067"
#define ICON_ttf_PLUS_SIGN u8"\uf055"
#define ICON_ttf_PUZZLE_PIECE u8"\uf12e"
#define ICON_ttf_QUESTION_SIGN u8"\uf059"
#define ICON_ttf_RANDOM u8"\uf074"
#define ICON_ttf_REFRESH u8"\uf021"
#define ICON_ttf_REMOVE u8"\uf00d"
#define ICON_ttf_REMOVE_SIGN u8"\uf057"
#define ICON_ttf_REPEAT u8"\uf01e"
#define ICON_ttf_RESIZE_FULL u8"\uf065"
#define ICON_ttf_RESIZE_SMALL u8"\uf066"
#define ICON_ttf_SAVE u8"\uf0c7"
#define ICON_ttf_STOP u8"\uf04d"
#define ICON_ttf_TABLET u8"\uf10a"
#define ICON_ttf_TAG u8"\uf02b"
#define ICON_ttf_TRASH u8"\uf014"
#define ICON_ttf_UNDO u8"\uf0e2"
#define ICON_ttf_UNLOCK_ALT u8"\uf13e"
#define ICON_ttf_ZOOM_IN u8"\uf00e"
#define ICON_ttf_ZOOM_OUT u8"\uf010"
