//Header Generated with https://github.com/aiekick/ImGuiFontStudio
//Based on https://github.com/juliettef/IconFontCppHeaders

#pragma once

#define FONT_ICON_FILE_NAME_ttf "fontawesome-webfont.ttf"

#define ICON_MIN_ttf 0xf00c
#define ICON_MAX_ttf 0xf13e

#define ICON_ttf_ANGLE_DOWN reinterpret_cast<const char*>(u8"\uf107")
#define ICON_ttf_ANGLE_LEFT reinterpret_cast<const char*>(u8"\uf104")
#define ICON_ttf_ANGLE_RIGHT reinterpret_cast<const char*>(u8"\uf105")
#define ICON_ttf_ANGLE_UP reinterpret_cast<const char*>(u8"\uf106")
#define ICON_ttf_BAN_CIRCLE reinterpret_cast<const char*>(u8"\uf05e")
#define ICON_ttf_BOOK reinterpret_cast<const char*>(u8"\uf02d")
#define ICON_ttf_CHEVRON_LEFT reinterpret_cast<const char*>(u8"\uf053")
#define ICON_ttf_CHEVRON_RIGHT reinterpret_cast<const char*>(u8"\uf054")
#define ICON_ttf_CLOUD_DOWNLOAD reinterpret_cast<const char*>(u8"\uf0ed")
#define ICON_ttf_CLOUD_UPLOAD reinterpret_cast<const char*>(u8"\uf0ee")
#define ICON_ttf_COG reinterpret_cast<const char*>(u8"\uf013")
#define ICON_ttf_CROP reinterpret_cast<const char*>(u8"\uf125")
#define ICON_ttf_DESKTOP reinterpret_cast<const char*>(u8"\uf108")
#define ICON_ttf_EDIT reinterpret_cast<const char*>(u8"\uf044")
#define ICON_ttf_EXCLAMATION_SIGN reinterpret_cast<const char*>(u8"\uf06a")
#define ICON_ttf_FACETIME_VIDEO reinterpret_cast<const char*>(u8"\uf03d")
#define ICON_ttf_FOLDER_CLOSE reinterpret_cast<const char*>(u8"\uf07b")
#define ICON_ttf_FOLDER_CLOSE_ALT reinterpret_cast<const char*>(u8"\uf114")
#define ICON_ttf_FOLDER_OPEN reinterpret_cast<const char*>(u8"\uf07c")
#define ICON_ttf_FOLDER_OPEN_ALT reinterpret_cast<const char*>(u8"\uf115")
#define ICON_ttf_GITHUB_ALT reinterpret_cast<const char*>(u8"\uf113")
#define ICON_ttf_HOME reinterpret_cast<const char*>(u8"\uf015")
#define ICON_ttf_INFO_SIGN reinterpret_cast<const char*>(u8"\uf05a")
#define ICON_ttf_LAPTOP reinterpret_cast<const char*>(u8"\uf109")
#define ICON_ttf_LOCATION_ARROW reinterpret_cast<const char*>(u8"\uf124")
#define ICON_ttf_MICROPHONE reinterpret_cast<const char*>(u8"\uf130")
#define ICON_ttf_MICROPHONE_OFF reinterpret_cast<const char*>(u8"\uf131")
#define ICON_ttf_MINUS reinterpret_cast<const char*>(u8"\uf068")
#define ICON_ttf_MINUS_SIGN reinterpret_cast<const char*>(u8"\uf056")
#define ICON_ttf_MOBILE_PHONE reinterpret_cast<const char*>(u8"\uf10b")
#define ICON_ttf_OK reinterpret_cast<const char*>(u8"\uf00c")
#define ICON_ttf_OK_SIGN reinterpret_cast<const char*>(u8"\uf058")
#define ICON_ttf_PAUSE reinterpret_cast<const char*>(u8"\uf04c")
#define ICON_ttf_PICTURE reinterpret_cast<const char*>(u8"\uf03e")
#define ICON_ttf_PLAY reinterpret_cast<const char*>(u8"\uf04b")
#define ICON_ttf_PLUS reinterpret_cast<const char*>(u8"\uf067")
#define ICON_ttf_PLUS_SIGN reinterpret_cast<const char*>(u8"\uf055")
#define ICON_ttf_PUZZLE_PIECE reinterpret_cast<const char*>(u8"\uf12e")
#define ICON_ttf_QUESTION_SIGN reinterpret_cast<const char*>(u8"\uf059")
#define ICON_ttf_RANDOM reinterpret_cast<const char*>(u8"\uf074")
#define ICON_ttf_REFRESH reinterpret_cast<const char*>(u8"\uf021")
#define ICON_ttf_REMOVE reinterpret_cast<const char*>(u8"\uf00d")
#define ICON_ttf_REMOVE_SIGN reinterpret_cast<const char*>(u8"\uf057")
#define ICON_ttf_REPEAT reinterpret_cast<const char*>(u8"\uf01e")
#define ICON_ttf_RESIZE_FULL reinterpret_cast<const char*>(u8"\uf065")
#define ICON_ttf_RESIZE_SMALL reinterpret_cast<const char*>(u8"\uf066")
#define ICON_ttf_SAVE reinterpret_cast<const char*>(u8"\uf0c7")
#define ICON_ttf_STOP reinterpret_cast<const char*>(u8"\uf04d")
#define ICON_ttf_TABLET reinterpret_cast<const char*>(u8"\uf10a")
#define ICON_ttf_TAG reinterpret_cast<const char*>(u8"\uf02b")
#define ICON_ttf_TRASH reinterpret_cast<const char*>(u8"\uf014")
#define ICON_ttf_UNDO reinterpret_cast<const char*>(u8"\uf0e2")
#define ICON_ttf_UNLOCK_ALT reinterpret_cast<const char*>(u8"\uf13e")
#define ICON_ttf_ZOOM_IN reinterpret_cast<const char*>(u8"\uf00e")
#define ICON_ttf_ZOOM_OUT reinterpret_cast<const char*>(u8"\uf010")
#define ICON_ttf_PLAY_CIRCLE reinterpret_cast<const char*>(u8"\uf144")
#define ICON_ttf_PAUSE_CIRCLE reinterpret_cast<const char*>(u8"\uf28b")
#define ICON_ttf_STOP_CIRCLE reinterpret_cast<const char*>(u8"\uf28d")
